### ISSUE TITLE
[1.6.0] RabbitMQ message are not acked, service stops working

### ISSUE THREAD

**Issue by Brutus5000** [cleborys/faf-league-service#71]
Currently on production the service takes up to 300 messages from the queue and reports them as done in the logs, but never releases them and never continues to work.

**Comment by BlackYps** [comment]
I'm sure the culprit is somewhere in here https://github.com/FAForever/faf-league-service/pull/68
It even had consequences for the tests, I just don't understand what changed that messages don't get processed properly anymore

**Comment by BlackYps** [comment]
@Askaholic have you encountered this problem before?

**Comment by Askaholic** [comment]
I don’t recall seeing that before. It could be that something changed with the library that requires you to update the code for it to keep working correctly. Idk, you could check the release notes for aio_pika and pampq.

You could also try reverting just the changes to rabbitmq, or revert the whole PR and then redo everything except the rabitmq update. Then you could at least isolate the issue.

**Comment by BlackYps** [comment]
I made some progress and isolated the problem to the update of the aio_pika library from 6.8.2 to 7.0
I'm just not sure what exactly goes wrong. The only code change that is needed for the update is for publishing messages, not reading them, so there must be something else going on.
See also #73

**Comment by BlackYps** [comment]
closed with #73
